import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    appName: "Civic AI",
    tagline: "Multilingual Government Scheme & Public Service Assistant",
    topBarGov: "National & State Government Scheme Gateway",
    helpline: "National Helpline: 1800-11-0031 / TN: 1800-425-1333",
    navHome: "Home",
    navFindBenefits: "Find Benefits",
    navAllSchemes: "All Schemes",
    navChat: "AI Assistant",
    navEval: "AI Evaluation",
    navAdmin: "Admin",
    navWishlist: "Wishlist",
    navMap: "Nearby Support",
    navTools: "Tools",
    navDocAnalyzer: "Doc Analyzer",
    navCompare: "Compare",
    heroTitle: "Find Government Schemes You Are Truly Eligible For",
    heroSubtitle: "Answer a few simple questions in English or தமிழ். Our zero-hallucination AI matches your profile against verified Central & State welfare initiatives.",
    heroTagline: "Know Your Scheme. Know Your Path.",
    startWizardBtn: "Find My Benefits",
    browseAllBtn: "Browse All Schemes",
    statsSchemes: "25+ Verified Schemes",
    statsAssistance: "₹10,000+ Cr Financial Aid",
    statsCentralState: "Central & State Covered",
    statsZeroHallucination: "100% Grounded in Official Sources",
    categoriesTitle: "Browse by Citizen Sector",
    catEducation: "Education & Scholarships",
    catAgriculture: "Agriculture & Farming",
    catWomen: "Women Empowerment",
    catHealthcare: "Healthcare & Insurance",
    catBusiness: "Business, MSME & Startups",
    catHousing: "Housing & Urban Welfare",
    catArtisans: "Artisans & Craftsmen",
    catSocialSecurity: "Pension & Social Security",
    catYouth: "Youth & Employment",
    feat1Title: "Government Scheme Explorer",
    feat1Desc: "Browse 500+ verified Central & State schemes with powerful filters",
    feat2Title: "AI-Powered Recommendations",
    feat2Desc: "Get personalized scheme matches based on your profile in seconds",
    feat3Title: "Document Rules Analyzer",
    feat3Desc: "Upload your documents & instantly know which schemes you qualify for",
    feat4Title: "Nearby Support & Live Map",
    feat4Desc: "Find CSCs, district offices, and banks near you on a live map",
    feat5Title: "Wishlist & Scheme Comparison",
    feat5Desc: "Save schemes you like and compare them side-by-side",
    feat6Title: "EMI & Financial Calculator",
    feat6Desc: "Calculate loan EMIs, check financial readiness & generate checklists",
    feat7Title: "Multilingual Support",
    feat7Desc: "Use Civic AI in English, தமிழ், or हिंदी — your language",
    feat8Title: "Official Portal Access",
    feat8Desc: "Direct links to official .gov.in portals for every scheme",
    
    // Wizard Form
    wizardTitle: "Citizen Eligibility Screening",
    wizardSubtitle: "Provide your details to analyze eligible central and state government benefits.",
    stepState: "State / District",
    stepAge: "Age",
    stepGender: "Gender",
    stepOccupation: "Occupation",
    stepIncome: "Annual Family Income (₹)",
    stepCategory: "Social Category (Caste)",
    stepEducation: "Education Qualification",
    stepGovtSchool: "Did you study in Govt School (Class 6-12)?",
    stepLandholding: "Do you own cultivable agricultural land?",
    stepDisability: "Person with Disability (PwD)?",
    stepRationCard: "Ration Card Type",
    analyzeBtn: "Analyze Eligible Schemes",
    analyzingBtn: "AI Matching Schemes...",
    
    // Results View
    resultsTitle: "Your Eligible Schemes Analysis",
    resultsSubtitle: "Based on your verified demographic profile",
    totalBenefitsMatched: "Total Financial Assistance Available",
    eligibleBadge: "Eligible",
    potentiallyEligibleBadge: "Potentially Eligible",
    notEligibleBadge: "Not Eligible",
    applyPortalBtn: "Apply on Official Govt Portal",
    viewDetailsBtn: "View Details & Checklist",
    askAIBtn: "Ask AI Assistant",
    resetWizardBtn: "Recalculate with New Profile",
    
    // Scheme Modal
    disclaimerTitle: "Official Government Disclaimer",
    disclaimerText: "Eligibility criteria and benefits are subject to official verification by the respective government department. Always apply directly via the official portal.",
    schemeOverview: "Scheme Overview & Objective",
    schemeBenefits: "Financial Aid & Welfare Benefits",
    schemeEligibility: "Mandatory Eligibility Conditions",
    schemeDocuments: "Required Documents Checklist",
    schemeSteps: "Application Procedure & Steps",
    schemeMode: "Application Mode",
    schemeHelpline: "Department Helpline",
    closeModal: "Close",
    openPortal: "Open Official Portal",
    chatAboutScheme: "Ask AI About This Scheme",
    saveWishlist: "Save to Wishlist",
    addCompare: "Add to Compare",
    shareScheme: "Share",
    nearbySupport: "Nearby Support",
    
    // Wishlist & Compare
    wishlistTitle: "My Saved Schemes",
    wishlistEmpty: "No schemes saved yet. Browse schemes and click the heart icon to save them.",
    removeWishlist: "Remove",
    compareSelected: "Compare Selected",
    
    // Map & Tools
    mapTitle: "Nearby Support Centers",
    mapSubtitle: "Find CSCs, district offices, banks & hospitals near you",
    findNearMe: "Find Near Me",
    toolsTitle: "Financial Tools",
    emiCalcTitle: "EMI Calculator",
    loanAmount: "Loan Amount (₹)",
    interestRate: "Interest Rate (% p.a.)",
    loanTenure: "Tenure (Months)",
    monthlyEMI: "Monthly EMI",
    totalInterest: "Total Interest",
    totalPayment: "Total Payment",
    finReadinessTitle: "Financial Readiness",
    docChecklistTitle: "Document Checklist Generator",
    docAnalyzerTitle: "Document Rules Analyzer",
    docAnalyzerSubtitle: "Upload your documents and Civic AI will identify which schemes you qualify for",
    uploadDoc: "Upload Document",
    analyzeDoc: "Analyze Documents",
    matchedSchemes: "Matched Schemes",
    compareTitle: "Scheme Comparison",
    compareSubtitle: "Select up to 3 schemes to compare side-by-side",
    selectScheme: "Select Scheme",

    // Contact & Messaging
    contactPhone: "WhatsApp / Mobile Number",
    contactEmail: "Email Address",
    contactName: "Full Name (as per Aadhaar)",
    contactPhoneNote: "Enter your mobile number to receive the required document checklist and direct portal link via SMS / WhatsApp.",
    receiveAlerts: "Send me WhatsApp / SMS updates & tracking alerts",
    dispatchSuccess: "Checklist & Application Dispatched to your Mobile!",
    sendToPhoneBtn: "Send Checklist to WhatsApp / SMS",

    // AI Chat
    chatTitle: "Civic AI Multi-Agent Assistant",
    chatSubtitle: "Grounded in official government rules and .gov.in sources",
    chatPlaceholder: "Ask in English, தமிழ் or हिंदी (e.g. 'How to apply for Pudhumai Penn?')...",
    chatSend: "Send",
    chatSources: "Verified Sources & Citations",
    chatSuggested1: "I am a student from Tamil Nadu with family income ₹2.5L. What schemes apply?",
    chatSuggested2: "What are the required documents for PM Vidyalaxmi Scheme?",
    chatSuggested3: "Am I eligible for PM Kisan if I own 2 acres of land in UP?",
    chatSuggested4: "How to get cashless hospitalization under Ayushman Bharat?"
  },
  ta: {
    appName: "Civic AI",
    tagline: "அரசு நலத்திட்டங்கள் மற்றும் பொது சேவைக்கான AI உதவியாளர்",
    topBarGov: "மத்திய & மாநில அரசு திட்டங்கள் வழிகாட்டி",
    helpline: "தேசிய உதவி எண்: 1800-11-0031 / TN உதவி எண்: 1800-425-1333",
    navHome: "முகப்பு", 
    navFindBenefits: "தகுதி காண்க", 
    navAllSchemes: "அனைத்து திட்டங்கள்",
    navChat: "AI உதவியாளர்", 
    navEval: "AI மதிப்பீடு", 
    navAdmin: "நிர்வாகம்",
    navWishlist: "விருப்பப் பட்டியல்", 
    navMap: "அருகிலுள்ள உதவி", 
    navTools: "கருவிகள்",
    navDocAnalyzer: "ஆவண பகுப்பாய்வு", 
    navCompare: "ஒப்பிடு",
    heroTitle: "நீங்கள் தகுதியான அரசு நலத்திட்டங்களை எளிதாக கண்டறியுங்கள்",
    heroSubtitle: "சில எளிய கேள்விகளுக்கு தமிழில் அல்லது ஆங்கிலத்தில் பதிலளிக்கவும். எங்களின் AI உங்கள் விவரங்களை ஆராய்ந்து திட்டங்களை கண்டறியும்.",
    heroTagline: "உங்கள் திட்டத்தை அறியுங்கள். உங்கள் பாதையை அறியுங்கள்.",
    startWizardBtn: "என் தகுதியை சரிபார்க்க", 
    browseAllBtn: "திட்டங்களை பார்க்க",
    statsSchemes: "25+ சரிபார்க்கப்பட்ட திட்டங்கள்", 
    statsAssistance: "₹10,000+ கோடி நிதி உதவி",
    statsCentralState: "மத்திய & மாநில திட்டங்கள்", 
    statsZeroHallucination: "100% அரசு ஆதாரங்கள்",
    categoriesTitle: "துறை வாரியாக திட்டங்கள்",
    catEducation: "கல்வி & கல்வி உதவித்தொகை", 
    catAgriculture: "விவசாயம் & உழவர் நலன்",
    catWomen: "பெண்கள் முன்னேற்றம்", 
    catHealthcare: "மருத்துவம் & காப்பீடு",
    catBusiness: "தொழில், MSME & ஸ்டார்ட்அப்", 
    catHousing: "வீட்டு வசதி திட்டம்",
    catArtisans: "கைவினைஞர்கள் & தொழிலாளர்கள்", 
    catSocialSecurity: "ஓய்வூதியம் & சமூக பாதுகாப்பு",
    catYouth: "இளைஞர் நலன் & வேலைவாய்ப்பு",
    feat1Title: "அரசு திட்ட ஆய்வாளர்", 
    feat1Desc: "500+ சரிபார்க்கப்பட்ட திட்டங்களை வடிகட்டி பார்க்கவும்",
    feat2Title: "AI-அடிப்படையிலான பரிந்துரைகள்", 
    feat2Desc: "உங்கள் சுயவிவரத்தின் அடிப்படையில் திட்டங்களை கண்டறியவும்",
    feat3Title: "ஆவண விதிகள் பகுப்பாய்வு", 
    feat3Desc: "ஆவணங்களை பதிவேற்றி உங்கள் தகுதியை உடனே அறியவும்",
    feat4Title: "அருகிலுள்ள உதவி & வரைபடம்", 
    feat4Desc: "அருகிலுள்ள CSC, அலுவலகங்கள் மற்றும் வங்கிகளை கண்டறியவும்",
    feat5Title: "விருப்பப் பட்டியல் & ஒப்பிடல்", 
    feat5Desc: "திட்டங்களை சேமித்து பக்கத்துக்கு பக்கம் ஒப்பிடவும்",
    feat6Title: "EMI & நிதி கணக்கிடு", 
    feat6Desc: "கடன் EMI கணக்கிட்டு நிதி தயார்நிலையை அறியவும்",
    feat7Title: "பல மொழி ஆதரவு", 
    feat7Desc: "தமிழ், ஆங்கிலம் அல்லது हिंदी-ல் Civic AI-ஐ பயன்படுத்தவும்",
    feat8Title: "அதிகாரப்பூர்வ போர்ட்டல் இணைப்பு", 
    feat8Desc: "ஒவ்வொரு திட்டத்திற்கும் நேரடி .gov.in இணைப்புகள்",
    
    // Wizard Form
    wizardTitle: "அரசு திட்டங்களுக்கான தகுதி சரிபார்ப்பு",
    wizardSubtitle: "உங்களின் தகவல்களை உள்ளிட்டு நீங்கள் பயன்பெறக்கூடிய நலத்திட்டங்களை கண்டறியவும்.",
    stepState: "மாநிலம் / மாவட்டம்", 
    stepAge: "வயது", 
    stepGender: "பாலினம்",
    stepOccupation: "தொழில்", 
    stepIncome: "குடும்ப ஆண்டு வருமானம் (₹)",
    stepCategory: "சமூக பிரிவு (வகுப்பு)", 
    stepEducation: "கல்வி தகுதி",
    stepGovtSchool: "அரசு பள்ளியில் படித்தவரா (வகுப்பு 6-12)?",
    stepLandholding: "சொந்தமாக விவசாய நிலம் உள்ளதா?", 
    stepDisability: "மாற்றுத்திறனாளியா?",
    stepRationCard: "குடும்ப அட்டை வகை", 
    analyzeBtn: "தகுதியான திட்டங்களை கண்டறிக",
    analyzingBtn: "AI திட்டங்களை ஆராய்கிறது...",
    
    // Results View
    resultsTitle: "உங்களுக்கான அரசு நலத்திட்டங்கள்",
    resultsSubtitle: "உங்களின் சுயவிவரத்தின் அடிப்படையில் கணக்கிடப்பட்டது",
    totalBenefitsMatched: "மொத்த நிதி உதவி மதிப்பு", 
    eligibleBadge: "தகுதியுடையவர்",
    potentiallyEligibleBadge: "வாய்ப்புள்ளது", 
    notEligibleBadge: "தகுதியற்றவர்",
    applyPortalBtn: "அரசு இணையதளத்தில் விண்ணப்பிக்க", 
    viewDetailsBtn: "விவரங்கள் & ஆவணங்கள்",
    askAIBtn: "AI உதவியாளரிடம் கேட்க", 
    resetWizardBtn: "மீண்டும் சரிபார்க்க",
    
    // Scheme Modal
    disclaimerTitle: "அரசு அதிகாரப்பூர்வ அறிவிப்பு",
    disclaimerText: "திட்டத்தின் தகுதிகள் மற்றும் நிபந்தனைகள் சம்பந்தப்பட்ட அரசு துறையின் சரிபார்ப்புக்கு உட்பட்டது. அதிகாரப்பூர்வ போர்ட்டல் மூலம் மட்டுமே விண்ணப்பிக்கவும்.",
    schemeOverview: "திட்டத்தின் நோக்கம் மற்றும் கண்ணோட்டம்",
    schemeBenefits: "வழங்கப்படும் பயன்கள் மற்றும் நிதி உதவி",
    schemeEligibility: "முக்கிய தகுதி நிபந்தனைகள்",
    schemeDocuments: "தேவையான ஆவணங்கள்",
    schemeSteps: "விண்ணப்பிக்கும் வழிமுறைகள்",
    schemeMode: "விண்ணப்பிக்கும் முறை",
    schemeHelpline: "உதவி எண்",
    closeModal: "மூடுக",
    openPortal: "அரசு போர்ட்டலை திறக்க",
    chatAboutScheme: "இந்த திட்டத்தை பற்றி AI-யிடம் கேட்க",
    saveWishlist: "விருப்பத்தில் சேர்க்க",
    addCompare: "ஒப்பிட சேர்க்க",
    shareScheme: "பகிர்",
    nearbySupport: "அருகிலுள்ள உதவி",
    wishlistTitle: "என் சேமித்த திட்டங்கள்",
    wishlistEmpty: "இன்னும் எந்த திட்டமும் சேமிக்கப்படவில்லை.",
    removeWishlist: "நீக்கு",
    compareSelected: "ஒப்பிடு",
    mapTitle: "அருகிலுள்ள உதவி மையங்கள்",
    mapSubtitle: "CSC, மாவட்ட அலுவலகங்கள், வங்கிகளை கண்டறியவும்",
    findNearMe: "என் அருகில் கண்டறி",
    toolsTitle: "நிதி கருவிகள்",
    emiCalcTitle: "EMI கணக்கீடு",
    loanAmount: "கடன் தொகை (₹)",
    interestRate: "வட்டி விகிதம் (% வருடத்திற்கு)",
    loanTenure: "கடன் காலம் (மாதங்கள்)",
    monthlyEMI: "மாதாந்திர EMI",
    totalInterest: "மொத்த வட்டி",
    totalPayment: "மொத்த கட்டணம்",
    finReadinessTitle: "நிதி தயார்நிலை",
    docChecklistTitle: "ஆவணப் பட்டியல் உருவாக்கி",
    docAnalyzerTitle: "ஆவண விதிகள் பகுப்பாய்வாளர்",
    docAnalyzerSubtitle: "ஆவணங்களை பதிவேற்றவும், Civic AI தகுதியான திட்டங்களை கண்டறியும்",
    uploadDoc: "ஆவணத்தை பதிவேற்று",
    analyzeDoc: "ஆவணங்களை பகுப்பாய்வு செய்",
    matchedSchemes: "பொருந்திய திட்டங்கள்",
    compareTitle: "திட்ட ஒப்பீடு",
    compareSubtitle: "3 திட்டங்கள் வரை தேர்ந்தெடுத்து ஒப்பிடவும்",
    selectScheme: "திட்டத்தை தேர்ந்தெடு",
    contactPhone: "வாட்ஸ்அப் / கைபேசி எண்",
    contactEmail: "மின்னஞ்சல் முகவரி",
    contactName: "முழுப் பெயர் (ஆதார் படி)",
    contactPhoneNote: "தேவையான ஆவணப் பட்டியல் மற்றும் நேரடி விண்ணப்ப லிங்க் உங்கள் வாட்ஸ்அப்-க்கு அனுப்பப்படும்.",
    receiveAlerts: "வாட்ஸ்அப் / எஸ்எம்எஸ் மூலம் நினைவூட்டல்களைப் பெறுக",
    dispatchSuccess: "ஆவணப் பட்டியல் & விண்ணப்பம் உங்கள் கைபேசிக்கு அனுப்பப்பட்டது!",
    sendToPhoneBtn: "வாட்ஸ்அப் / எஸ்எம்எஸ்-ல் ஆவணப் பட்டியல் பெற",
    chatTitle: "Civic AI உதவியாளர்",
    chatSubtitle: "அதிகாரப்பூர்வ அரசு விதிகள் மற்றும் .gov.in இணையதள ஆதாரங்களுடன்",
    chatPlaceholder: "தமிழ், ஆங்கிலம் அல்லது हिंदी-ல் கேட்கலாம்...",
    chatSend: "அனுப்பு",
    chatSources: "அரசு இணையதள ஆதாரங்கள்",
    chatSuggested1: "தமிழ்நாடு மாணவி, குடும்ப வருமானம் ₹2.5 லட்சம். என்ன திட்டங்கள் கிடைக்கும்?",
    chatSuggested2: "பிஎம் வித்யாலக்ஷ்மி திட்டத்திற்கு என்ன ஆவணங்கள் தேவை?",
    chatSuggested3: "2 ஏக்கர் நிலம் உள்ள உழவருக்கு பிஎம் கிசான் கிடைக்குமா?",
    chatSuggested4: "ஆயுஷ்மான் பாரத் மூலம் இலவச சிகிச்சை பெறுவது எப்படி?"
  },
  hi: {
    appName: "Civic AI",
    tagline: "बहुभाषी सरकारी योजना और नागरिक सेवा सहायक",
    topBarGov: "राष्ट्रीय और राज्य सरकारी योजना गेटवे",
    helpline: "राष्ट्रीय हेल्पलाइन: 1800-11-0031",
    navHome: "होम", navFindBenefits: "लाभ खोजें", navAllSchemes: "सभी योजनाएं",
    navChat: "AI सहायक", navEval: "AI मूल्यांकन", navAdmin: "एडमिन",
    navWishlist: "विशलिस्ट", navMap: "नजदीकी सहायता", navTools: "टूल्स",
    navDocAnalyzer: "दस्तावेज़ विश्लेषण", navCompare: "तुलना",
    heroTitle: "अपनी पात्रता की सरकारी योजनाएं खोजें",
    heroSubtitle: "कुछ सरल प्रश्नों का उत्तर दें। हमारा AI आपकी प्रोफ़ाइल के अनुसार केंद्र और राज्य योजनाएं मिलाता है।",
    heroTagline: "अपनी योजना जानें। अपना रास्ता जानें।",
    startWizardBtn: "मेरे लाभ खोजें", browseAllBtn: "सभी योजनाएं देखें",
    statsSchemes: "25+ सत्यापित योजनाएं", statsAssistance: "₹10,000+ करोड़ वित्तीय सहायता",
    statsCentralState: "केंद्र और राज्य योजनाएं", statsZeroHallucination: "100% आधिकारिक स्रोत",
    categoriesTitle: "क्षेत्र के अनुसार योजनाएं",
    catEducation: "शिक्षा और छात्रवृत्ति", catAgriculture: "कृषि और किसान कल्याण",
    catWomen: "महिला सशक्तिकरण", catHealthcare: "स्वास्थ्य और बीमा",
    catBusiness: "व्यवसाय, MSME और स्टार्टअप", catHousing: "आवास और शहरी कल्याण",
    catArtisans: "कारीगर और शिल्पकार", catSocialSecurity: "पेंशन और सामाजिक सुरक्षा",
    catYouth: "युवा और रोजगार",
    feat1Title: "सरकारी योजना एक्सप्लोरर", feat1Desc: "500+ सत्यापित योजनाएं फ़िल्टर के साथ",
    feat2Title: "AI-संचालित अनुशंसाएं", feat2Desc: "प्रोफ़ाइल के आधार पर व्यक्तिगत योजना मिलान",
    feat3Title: "दस्तावेज़ नियम विश्लेषक", feat3Desc: "दस्तावेज़ अपलोड करें और योग्य योजनाएं जानें",
    feat4Title: "नजदीकी सहायता और लाइव मैप", feat4Desc: "CSC, जिला कार्यालय और बैंक मैप पर खोजें",
    feat5Title: "विशलिस्ट और तुलना", feat5Desc: "योजनाएं सेव करें और साथ-साथ तुलना करें",
    feat6Title: "EMI और वित्तीय कैलकुलेटर", feat6Desc: "लोन EMI और वित्तीय तैयारी चेक करें",
    feat7Title: "बहुभाषी समर्थन", feat7Desc: "English, தமிழ் या हिंदी में उपयोग करें",
    feat8Title: "आधिकारिक पोर्टल एक्सेस", feat8Desc: "हर योजना के लिए .gov.in पोर्टल लिंक",
    wizardTitle: "नागरिक पात्रता स्क्रीनिंग", wizardSubtitle: "अपनी जानकारी भरें और लाभ खोजें।",
    stepState: "राज्य / जिला", stepAge: "आयु", stepGender: "लिंग",
    stepOccupation: "व्यवसाय", stepIncome: "वार्षिक पारिवारिक आय (₹)",
    stepCategory: "सामाजिक श्रेणी (जाति)", stepEducation: "शैक्षणिक योग्यता",
    stepGovtSchool: "क्या आपने सरकारी स्कूल में पढ़ा?",
    stepLandholding: "क्या आपके पास कृषि भूमि है?", stepDisability: "दिव्यांगजन (PwD)?",
    stepRationCard: "राशन कार्ड प्रकार", analyzeBtn: "पात्र योजनाएं खोजें",
    analyzingBtn: "AI योजनाएं खोज रहा है...",
    resultsTitle: "आपकी पात्र योजनाएं", resultsSubtitle: "आपकी प्रोफ़ाइल के आधार पर",
    totalBenefitsMatched: "कुल वित्तीय सहायता", eligibleBadge: "पात्र",
    potentiallyEligibleBadge: "संभावित पात्र", notEligibleBadge: "अपात्र",
    applyPortalBtn: "आधिकारिक पोर्टल पर आवेदन करें", viewDetailsBtn: "विवरण देखें",
    askAIBtn: "AI से पूछें", resetWizardBtn: "पुनर्गणना करें",
    disclaimerTitle: "आधिकारिक सरकारी अस्वीकरण",
    disclaimerText: "पात्रता मानदंड संबंधित विभाग की सत्यापन के अधीन हैं।",
    schemeOverview: "योजना अवलोकन", schemeBenefits: "वित्तीय सहायता और लाभ",
    schemeEligibility: "पात्रता शर्तें", schemeDocuments: "आवश्यक दस्तावेज़",
    schemeSteps: "आवेदन प्रक्रिया", schemeMode: "आवेदन मोड",
    schemeHelpline: "हेल्पलाइन", closeModal: "बंद करें", openPortal: "पोर्टल खोलें",
    chatAboutScheme: "इस योजना के बारे में AI से पूछें",
    saveWishlist: "विशलिस्ट में सेव करें", addCompare: "तुलना में जोड़ें",
    shareScheme: "साझा करें", nearbySupport: "नजदीकी सहायता",
    wishlistTitle: "मेरी सेव योजनाएं", wishlistEmpty: "अभी कोई योजना सेव नहीं।",
    removeWishlist: "हटाएं", compareSelected: "तुलना करें",
    mapTitle: "नजदीकी सहायता केंद्र", mapSubtitle: "CSC, जिला कार्यालय, बैंक खोजें",
    findNearMe: "मेरे नजदीक खोजें",
    toolsTitle: "वित्तीय टूल्स", emiCalcTitle: "EMI कैलकुलेटर",
    loanAmount: "ऋण राशि (₹)", interestRate: "ब्याज दर (% प्रति वर्ष)",
    loanTenure: "अवधि (महीने)", monthlyEMI: "मासिक EMI",
    totalInterest: "कुल ब्याज", totalPayment: "कुल भुगतान",
    finReadinessTitle: "वित्तीय तैयारी", docChecklistTitle: "चेकलिस्ट जेनरेटर",
    docAnalyzerTitle: "दस्तावेज़ विश्लेषक",
    docAnalyzerSubtitle: "दस्तावेज़ अपलोड करें, Civic AI पात्र योजनाएं पहचानेगा",
    uploadDoc: "दस्तावेज़ अपलोड करें", analyzeDoc: "विश्लेषण करें",
    matchedSchemes: "मिलान योजनाएं",
    compareTitle: "योजना तुलना", compareSubtitle: "3 योजनाओं तक तुलना करें",
    selectScheme: "योजना चुनें",
    contactPhone: "WhatsApp / मोबाइल", contactEmail: "ईमेल", contactName: "पूरा नाम",
    contactPhoneNote: "SMS / WhatsApp पर दस्तावेज़ सूची भेजी जाएगी।",
    receiveAlerts: "अपडेट भेजें", dispatchSuccess: "मोबाइल पर भेजा गया!",
    sendToPhoneBtn: "WhatsApp पर भेजें",
    chatTitle: "Civic AI मल्टी-एजेंट सहायक",
    chatSubtitle: "आधिकारिक सरकारी नियमों और .gov.in स्रोतों पर आधारित",
    chatPlaceholder: "English, தமிழ் या हिंदी में पूछें...",
    chatSend: "भेजें", chatSources: "सत्यापित स्रोत",
    chatSuggested1: "मैं UP का किसान हूं, 2 एकड़ जमीन। PM Kisan मिलेगा?",
    chatSuggested2: "पीएम विद्यालक्ष्मी के लिए दस्तावेज़ क्या चाहिए?",
    chatSuggested3: "महिला उद्यमी के लिए कौन सी योजनाएं हैं?",
    chatSuggested4: "आयुष्मान भारत में मुफ्त इलाज कैसे पाएं?"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try { return localStorage.getItem('civicai_lang') || 'en'; }
    catch { return 'en'; }
  });

  const LANG_CYCLE = ['en', 'ta', 'hi'];

  const toggleLanguage = () => {
    const currentIdx = LANG_CYCLE.indexOf(language);
    const next = LANG_CYCLE[(currentIdx + 1) % LANG_CYCLE.length];
    setLanguage(next);
    try { localStorage.setItem('civicai_lang', next); } catch {}
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  const getLangLabel = () => {
    if (language === 'en') return 'தமிழ் (TA)';
    if (language === 'ta') return 'हिंदी (HI)';
    return 'English (EN)';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, getLangLabel }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
